[CmdletBinding()]
param(
  [string]$Env = '.env',
  [switch]$Help
)

$ErrorActionPreference = 'Stop'
$lib = Join-Path $PSScriptRoot 'lib'
Import-Module (Join-Path $lib 'Common.psm1') -Force

if ($Help) {
  @'
Usage:
  .\scripts\windows\init-config.ps1

Options:
  -Env <path>   Write config to another path. Default: .env in project root.
'@ | Write-Host
  exit 0
}

function Read-ExistingEnv {
  param([Parameter(Mandatory)][string]$Path)

  $map = [ordered]@{}
  if (-not (Test-Path -LiteralPath $Path)) {
    return $map
  }

  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith('#')) {
      return
    }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) {
      return
    }
    $key = $line.Substring(0, $idx).Trim()
    $value = $line.Substring($idx + 1).Trim()
    if ($value.Length -ge 2 -and (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'")))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $map[$key] = $value
  }
  return $map
}

function Get-ConfigValue {
  param(
    [Parameter(Mandatory)][System.Collections.IDictionary]$Map,
    [Parameter(Mandatory)][string]$Key,
    [AllowNull()][string]$Default
  )

  if ($Map.Contains($Key)) {
    return [string]$Map[$Key]
  }
  return $Default
}

function Read-ConfigValue {
  param(
    [Parameter(Mandatory)][string]$Label,
    [AllowNull()][string]$Default,
    [switch]$Required
  )

  while ($true) {
    if ([string]::IsNullOrWhiteSpace($Default)) {
      $value = Read-Host "$Label"
    } else {
      $value = Read-Host "$Label [$Default]"
      if ([string]::IsNullOrWhiteSpace($value)) {
        $value = $Default
      }
    }

    if (-not $Required -or -not [string]::IsNullOrWhiteSpace($value)) {
      return [string]$value
    }
    Write-Host 'This value is required.'
  }
}

function Read-NetworkId {
  param([AllowNull()][string]$Default)

  while ($true) {
    $value = Read-ConfigValue -Label 'ZeroTier network ID, 16 hex chars' -Default $Default -Required
    if ($value -match '^[0-9a-fA-F]{16}$') {
      return $value
    }
    Write-Host 'The network ID must be 16 hex chars, for example 0123456789abcdef.'
  }
}

function Read-YesNo {
  param(
    [Parameter(Mandatory)][string]$Label,
    [Parameter(Mandatory)][bool]$Default
  )

  if ($Default) {
    $suffix = '[Y/n]'
  } else {
    $suffix = '[y/N]'
  }
  while ($true) {
    $answer = (Read-Host "$Label $suffix").Trim().ToLowerInvariant()
    if (-not $answer) {
      return $Default
    }
    switch ($answer) {
      'y' { return $true }
      'yes' { return $true }
      'n' { return $false }
      'no' { return $false }
      default { Write-Host 'Please enter y or n.' }
    }
  }
}

$resolved = Resolve-ZtgPath $Env
$current = Read-ExistingEnv -Path $resolved

if (Test-Path -LiteralPath $resolved) {
  Write-ZtgInfo "Existing config found: $resolved"
  Write-ZtgInfo 'Press Enter to keep the current value.'
}

$networkId = Read-NetworkId -Default (Get-ConfigValue -Map $current -Key 'ZEROTIER_NETWORK_ID' -Default '')
$subnet = Read-ConfigValue -Label 'ZeroTier subnet' -Default (Get-ConfigValue -Map $current -Key 'ZEROTIER_SUBNET' -Default '10.246.77.0/24') -Required
$ubuntuIp = Read-ConfigValue -Label 'Ubuntu ZeroTier IP' -Default (Get-ConfigValue -Map $current -Key 'UBUNTU_ZT_IP' -Default '10.246.77.1') -Required
$homeIp = Read-ConfigValue -Label 'Home Windows ZeroTier IP' -Default (Get-ConfigValue -Map $current -Key 'HOME_PC_ZT_IP' -Default '10.246.77.10') -Required
$workIp = Read-ConfigValue -Label 'Work Windows ZeroTier IP' -Default (Get-ConfigValue -Map $current -Key 'WORK_PC_ZT_IP' -Default '10.246.77.20') -Required
$proxyPort = Read-ConfigValue -Label 'Proxy port' -Default (Get-ConfigValue -Map $current -Key 'PROXY_PORT' -Default '10808') -Required

$proxyUsername = Get-ConfigValue -Map $current -Key 'PROXY_USERNAME' -Default ''
$proxyPassword = Get-ConfigValue -Map $current -Key 'PROXY_PASSWORD' -Default ''
$authDefault = -not [string]::IsNullOrWhiteSpace($proxyUsername) -and -not [string]::IsNullOrWhiteSpace($proxyPassword)

if (Read-YesNo -Label 'Enable proxy username and password' -Default $authDefault) {
  $proxyUsername = Read-ConfigValue -Label 'Proxy username' -Default $proxyUsername -Required
  $proxyPassword = Read-ConfigValue -Label 'Proxy password' -Default $proxyPassword -Required
} else {
  $proxyUsername = ''
  $proxyPassword = ''
}

$content = @"
# ZeroTier Gateway config.
# Generated by scripts/ubuntu/init-config.sh or scripts/windows/init-config.ps1.

ZEROTIER_NETWORK_ID=$networkId
ZEROTIER_SUBNET=$subnet
UBUNTU_ZT_IP=$ubuntuIp
HOME_PC_ZT_IP=$homeIp
WORK_PC_ZT_IP=$workIp

PROXY_BIND_IP=$ubuntuIp
PROXY_PORT=$proxyPort
PROXY_USERNAME=$proxyUsername
PROXY_PASSWORD=$proxyPassword

PROXY_MODE=$(Get-ConfigValue -Map $current -Key 'PROXY_MODE' -Default 'manual')
PROXY_DEFAULT=$(Get-ConfigValue -Map $current -Key 'PROXY_DEFAULT' -Default 'proxy')
DIRECT_DOMAINS=$(Get-ConfigValue -Map $current -Key 'DIRECT_DOMAINS' -Default 'localhost,*.local')
DIRECT_DOMAIN_SUFFIXES=$(Get-ConfigValue -Map $current -Key 'DIRECT_DOMAIN_SUFFIXES' -Default '.local')
DIRECT_IP_CIDRS=$(Get-ConfigValue -Map $current -Key 'DIRECT_IP_CIDRS' -Default '10.246.77.0/24,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16')
DIRECT_PROCESS_GROUPS=$(Get-ConfigValue -Map $current -Key 'DIRECT_PROCESS_GROUPS' -Default '')
DIRECT_PROCESS_NAMES=$(Get-ConfigValue -Map $current -Key 'DIRECT_PROCESS_NAMES' -Default '')
DIRECT_PROCESS_PATHS=$(Get-ConfigValue -Map $current -Key 'DIRECT_PROCESS_PATHS' -Default '')
DIRECT_PROCESS_PATH_REGEX=$(Get-ConfigValue -Map $current -Key 'DIRECT_PROCESS_PATH_REGEX' -Default '')

ENABLE_RELAY=$(Get-ConfigValue -Map $current -Key 'ENABLE_RELAY' -Default 'false')
RELAY_PORT=$(Get-ConfigValue -Map $current -Key 'RELAY_PORT' -Default '443')
RELAY_FORCE=$(Get-ConfigValue -Map $current -Key 'RELAY_FORCE' -Default 'false')

REMOTE_PORTS=$(Get-ConfigValue -Map $current -Key 'REMOTE_PORTS' -Default '3389')
LOCAL_PROXY_PORT=$(Get-ConfigValue -Map $current -Key 'LOCAL_PROXY_PORT' -Default '20808')
"@

$dir = Split-Path -Parent $resolved
if ($dir) {
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($resolved, $content, $utf8NoBom)

Write-ZtgInfo "Config generated: $resolved"
Write-ZtgInfo 'Next Ubuntu command: sudo bash scripts/ubuntu/install.sh --dry-run'
Write-ZtgInfo 'Windows command: .\scripts\windows\setup.ps1 -Role Home or -Role Work'
